package main

import (
	"fmt"
	"strings"
)

func main() {
	slideWindow(" AAEDGFEFDGACGBDBEBGDDBCABECDEGEAGGCGCFEAEDEEGGCFFFFDEAECCGCAFBCAGEBGABCGEGBBGEFBAEGCACACBGCCBGBGEFGCEGFGDAAAECDFDGDFFBEGFDDAGABACDGGDBAAAAGBEFGGGAFECCAECGEDDEFBFEGFDGGBFFGCGGBDGDDFDAEAFGDCBBFGGFCDFBEEGGBGCFEFGBAAGDEADDACEGADFGBGAFEDBCDBGEEFCDFCGEFFFGGCCGGGCCCCECDBGGEAACFEGBEEEBFEGFFFGEDABCEEAGFAGCDCADCAFCEABBABBBBACBBFEABAEFECBEDFGEDDFFABBGGACECBCEGCFABDFCGDAGFCGADFFDBBEBBCDEFFDCDDDDACGGBAAFCFCGCBBCACDCCFCDCFFFEGGCFFGFFDFCAEFBBDCFEEEDCBCEGCBDAEBFFAFAGCGCGDFGECGFBBDGDFGGGCCGEECAEGAFGCFCEEAAAFFABFBAECBAGGBFAABGABFFADABCEAGCBFAEAABBGDFFDBABDEGDBGBFGFGAFCDDGDGFBFFGBEGFACFCBEDABCADABBEABCDBCBBGDFDGBCDBAGACEGBDEGCCABEEDEDACCAEFEFEGBEEADEBFACDBAFCDEFDFBGEFFBDCEDBDBFFDCADFDAFDEFDGBAAGEAFADFGGDBFGDDDCFGFDAFGAFBDGFFABDAFCDGEBBEGBGGCDFEBAFFDDGDECGEGGGDAFDABEGAFAGDBABFGADACEABECDGGBCCECCBADCDGEDGCFBGDADEDFEACECFECFCDFECGFCBDBCGCGFGFBBDBDEABCGBFFDFCACBFGFGACDCDFFBFEDGABDBCBBEFDECFEFCACBEFDEBDACABACCEAEFGAFDDFCCCGDGGGECGFAAADDGCGEFEGEBEFECAACBCGGDFDFBAGBFABEFDDDDFFGACBCACFGBFGBFGBDCBCCAEAAEDEEDEEAFF")

}
func slideWindow(s string) {
	runes := []rune(s)
	for i := 1; i < len(runes); i = i + 7 {
		inicio := i
		fim := i + 7
		this := runes[inicio:fim]
		if strings.ContainsRune(string(this), 'A') && strings.ContainsRune(string(this), 'B') && strings.ContainsRune(string(this), 'C') && strings.ContainsRune(string(this), 'D') && strings.ContainsRune(string(this), 'E') && strings.ContainsRune(string(this), 'F') && strings.ContainsRune(string(this), 'G') {
			fmt.Println(string(this))
			break
		}
	}
}
